### ISSUE TITLE
errata?

### ISSUE THREAD

**Issue by leonardgithub** [xeb/fastText-docker#3]
in README.md, it seems a space should be between the 'docker' and '#' mark.
docker pull xebxeb/fasttext-docker# <-- latest is devel
-->
docker pull xebxeb/fasttext-docker # <-- latest is devel
Right?

**Comment by xeb** [comment]
Yeah, good point.  The comment is confusing in the code block anyways.  Its mentioned in the README, so I just modified that.  Thanks for pointing it out!
